### ISSUE TITLE
Also implement `retain_mut` for other collections

### ISSUE THREAD

**Issue by jonhoo** [upsuper/retain_mut#1]
`VecDeque` in particular comes to mind?

**Comment by Boscop** [comment]
Yes, please :)

**Comment by upsuper** [comment]
Sorry I somehow missed the issue (because I somehow didn't watch my own project before)... Contributions are always welcome, and I'll try to look into this as well.

**Comment by upsuper** [comment]
This has been fixed in b15978556002b3942e3daf30ebf7eb803e1c52bd and the new version has been published as 0.1.1 on crates.io.
