### ISSUE TITLE
Suggestion: Add function that takes a `RangeBounds` arg like `drain`

### ISSUE THREAD

**Issue by Boscop** [upsuper/retain_mut#2]
Suggestion: Please add function that takes a `RangeBounds` arg like `drain`, so that that version of `retain_mut` can be invoked on a sub-slice of a Vec.
E.g.
```rust
v.retain_mut_range(i.., pred);
```

**Comment by upsuper** [comment]
I can see this being useful.

However, this crates is just trying to provide the proper API for the existing `retain` functions in `std`, and thus its implementation is simply a copy of `std` implementation with minor change, which means it doesn't need much auditing and testing itself.

Given that, I'm reluctant to introduce any non-trivial code which doesn't already exist in `std` into this crate. I think this kind of functions should probably be in its own crate, and / or proposed to `std`.
